import { useCallback, useId, useRef, useState, type MouseEvent as ReactMouseEvent } from 'react';
import { ArrowUp, Sparkles } from 'lucide-react';
import type { AppLang, Translator } from '../i18n';
import { AssistantDialog, type AssistantReply, type Exchange } from './AssistantDialog';

/**
 * The landing page's "Ask AI assistant", placed and sized after mongodb.com's.
 *
 * On the page it is a box that looks like the question field and a row of common
 * questions; either opens the conversation dialog (AssistantDialog), a common
 * question with its answer already added.
 *
 * Free-form questions go to /api/assistant (Mistral, EU-hosted), each on its own:
 * the conversation on screen is for the visitor, and the server never sees earlier
 * turns. The starter questions are answered here instead - instantly, at no cost,
 * and word for word as written - and they are what the page falls back to whenever
 * the assistant cannot answer: no key configured, a limit reached, the server or the
 * network down, a timeout, a reply in any shape but the expected one. The visitor
 * never sees an error, only a note pointing at those questions.
 *
 * The conversation lives here, not in the dialog, so closing and reopening the
 * dialog keeps it - and an answer that arrives after the dialog was closed is there
 * when it opens again.
 */

// English strings are the i18n keys.
const STARTERS: [question: string, answer: string][] = [
  [
    'What does this platform do?',
    'It connects UXO survey results with the crews who dig. The office loads the anomaly targets from a magnetometer or georadar survey, the Field App takes them to the crew on a tablet or phone, and every excavation result comes back to the office for the Dashboard and reports.',
  ],
  [
    'Does the Field App work without a connection?',
    'Yes. Targets are kept on the device and excavation logs are queued there, then synchronised with the office as soon as the connection returns. The app can be installed on the device like a native app.',
  ],
  [
    'What does the Dashboard show?',
    'Clearance progress (targets investigated against pending, excavated volume), findings by type, Sohle status by finding, sensor accuracy - evaluated against excavated depth - and target dimensions, filtered by project, instrument and category. Results export as PDF or CSV.',
  ],
  [
    'How do I get access?',
    'Choose Get access at the top of this page to request an account. New accounts start with the Field App; access to the Dashboard is granted by an administrator.',
  ],
];

const MAX_CHARS = 500;       // the server's cap, so a long question is never sent to be refused
const TIMEOUT_MS = 30_000;   // the server gives Mistral 20s; this covers that and the trip

export function AskAssistant({ t, lang }: { t: Translator; lang: AppLang }) {
  const [exchanges, setExchanges] = useState<Exchange[]>([]);
  const [draft, setDraft] = useState('');
  const [opener, setOpener] = useState<HTMLElement | null>(null);
  const nextId = useRef(0);
  const noteId = useId();
  const note = t("Answers are generated by AI on Mistral's EU servers and can be wrong. Please do not enter personal data.");

  // One question at a time, as before: the send button waits for the pending answer.
  const busy = exchanges.some(ex => ex.reply.kind === 'loading');

  const settle = (id: number, reply: AssistantReply) =>
    setExchanges(list => list.map(ex => (ex.id === id ? { ...ex, reply } : ex)));

  const ask = async () => {
    const q = draft.trim();
    if (!q || busy) return;
    const id = ++nextId.current;
    setDraft('');
    setExchanges(list => [...list, { id, question: q, reply: { kind: 'loading' } }]);

    let reply: AssistantReply = { kind: 'fallback', limited: false };
    const controller = new AbortController();
    const timer = window.setTimeout(() => controller.abort(), TIMEOUT_MS);
    try {
      const res = await fetch('/api/assistant', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question: q, lang }),
        signal: controller.signal,
      });
      if (res.ok) {
        const data = await res.json();
        if (data?.status === 'ok' && typeof data.answer === 'string' && data.answer.trim()) {
          reply = { kind: 'answer', text: data.answer.trim() };
        } else if (data?.status === 'limited') {
          reply = { kind: 'fallback', limited: true };
        }
      }
    } catch {
      // Offline, timed out, or not JSON: the fallback set above stands.
    } finally {
      window.clearTimeout(timer);
    }
    settle(id, reply);
  };

  const addStarter = (index: number) => {
    const id = ++nextId.current;
    setExchanges(list => [...list, { id, question: '', reply: { kind: 'starter', index } }]);
  };

  const openFrom = (e: ReactMouseEvent<HTMLElement>, starter?: number) => {
    setOpener(e.currentTarget);
    if (starter !== undefined) addStarter(starter);
  };

  const close = useCallback(() => setOpener(null), []);

  return (
    <div className="ask">
      {/* Hidden note keeps aria-describedby working but is invisible on the page */}
      <span id={noteId} className="ask-note ask-note--hidden" aria-hidden="true" />

      <button
        type="button"
        className="ask-box ask-trigger"
        onClick={e => openFrom(e)}
        aria-haspopup="dialog"
        aria-describedby={noteId}
      >
        <Sparkles size={20} className="ask-icon" aria-hidden="true" />
        <span className="ask-trigger-text">{t('Ask the AI assistant')}</span>
        <span className="ask-send" aria-hidden="true">
          <ArrowUp size={18} />
        </span>
      </button>

      {opener && (
        <AssistantDialog
          t={t}
          starters={STARTERS}
          exchanges={exchanges}
          draft={draft}
          busy={busy}
          maxChars={MAX_CHARS}
          noteText={note}
          opener={opener}
          onDraftChange={setDraft}
          onAsk={ask}
          onStarter={addStarter}
          onClose={close}
        />
      )}
    </div>
  );
}
